/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/components/Dashboard': RouteRecordInfo<'/admin/components/Dashboard', '/admin/components/Dashboard', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/AddItemDialog': RouteRecordInfo<'/admin/components/dialogs/AddItemDialog', '/admin/components/dialogs/AddItemDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteItemDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteItemDialog', '/admin/components/dialogs/DeleteItemDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditItemDialog': RouteRecordInfo<'/admin/components/dialogs/EditItemDialog', '/admin/components/dialogs/EditItemDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/InventoryTable': RouteRecordInfo<'/admin/components/InventoryTable', '/admin/components/InventoryTable', Record<never, never>, Record<never, never>>,
    '/admin/components/TableQRCodeGenerator': RouteRecordInfo<'/admin/components/TableQRCodeGenerator', '/admin/components/TableQRCodeGenerator', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/InventoryView': RouteRecordInfo<'/admin/InventoryView', '/admin/InventoryView', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/cashier/CashierHistoryView': RouteRecordInfo<'/cashier/CashierHistoryView', '/cashier/CashierHistoryView', Record<never, never>, Record<never, never>>,
    '/cashier/CashierOrdersView': RouteRecordInfo<'/cashier/CashierOrdersView', '/cashier/CashierOrdersView', Record<never, never>, Record<never, never>>,
    '/cashier/components/OrderActions': RouteRecordInfo<'/cashier/components/OrderActions', '/cashier/components/OrderActions', Record<never, never>, Record<never, never>>,
    '/cashier/components/OrderCard': RouteRecordInfo<'/cashier/components/OrderCard', '/cashier/components/OrderCard', Record<never, never>, Record<never, never>>,
    '/cashier/components/OrderFilters': RouteRecordInfo<'/cashier/components/OrderFilters', '/cashier/components/OrderFilters', Record<never, never>, Record<never, never>>,
    '/customer/LandingPage': RouteRecordInfo<'/customer/LandingPage', '/customer/LandingPage', Record<never, never>, Record<never, never>>,
    '/customer/Menu': RouteRecordInfo<'/customer/Menu', '/customer/Menu', Record<never, never>, Record<never, never>>,
    '/customer/ReviewOrder': RouteRecordInfo<'/customer/ReviewOrder', '/customer/ReviewOrder', Record<never, never>, Record<never, never>>,
    '/customer/WaitingPage': RouteRecordInfo<'/customer/WaitingPage', '/customer/WaitingPage', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/otherTab/Page1View': RouteRecordInfo<'/otherTab/Page1View', '/otherTab/Page1View', Record<never, never>, Record<never, never>>,
  }
}
